version: "3.2"
services:
  api:
    image: fastify-api
    container_name: fastify-api

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8080:8080

    environment:
      REDIS_HOST: redis

    depends_on:
      - redis

    links:
      - redis

  api2:
    image: fastify-api
    container_name: fastify-api2

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8081:8080

    environment:
      REDIS_HOST: redis

    depends_on:
      - redis

    links:
      - redis

  redis:
    image: redis:7.0.5-alpine
    container_name: redis

    ports:
      - 6379:6379

    environment:
      - ALLOW_EMPTY_PASSWORD=yes

    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
